### PR TITLE
2.75 Manual

### PR DESCRIPTION
**Pull request by GregorySchwing**
2.75 manual

### CODE REVIEW

**Comment by GregorySchwing** [comment]
@LSchwiebert I have implemented the changes Brad and Mohammad requested.  This is ready to merge and release 2.75.

**Review by LSchwiebert — CHANGES_REQUESTED** [review]
Two small changes.

1. Could you fix the misspelling of "template" in README.md? I know you didn't make this typo, but let's fix it while we are working on things.

2. In the Release notes, we should mention that we switched from the GPL 3.0 License to the MIT License. People should upgrade only if they are comfortable with running code under this new license.

**Comment by GregorySchwing** [comment]
> Two small changes.
> 
> 1. Could you fix the misspelling of "template" in README.md? I know you didn't make this typo, but let's fix it while we are working on things.
> 2. In the Release notes, we should mention that we switched from the GPL 3.0 License to the MIT License. People should upgrade only if they are comfortable with running code under this new license.

Done.

**Review by LSchwiebert — APPROVED** [review]

**Comment by LSchwiebert** [comment]
Looks good. Thanks for getting these changes made.

**Pull request merged**
